// Generated by LiveScript 1.3.0
(function(){
  var chainCtrl, myDummy;
  chainCtrl = function($window, $scope, $dummy, $goban){
    $scope.goban = $goban;
    $scope.goban.data = $dummy;
    $scope.goban.load($goban.myI);
    $scope.navHeight = 50;
    $scope.countHeight = function(){
      return $window.innerHeight - 40;
    };
    $scope.countWidth = function(){
      $window.innerWidth - 220;
      return $scope.myOpts = ['gl_book', 'gl_demo', 'gl_history', 'gl_intro', 'gl_join',
                             'gl_issue', 'gl_link', 'gl_news', 'gl_movement',
                             'gl_print', 'gl_tool'];
    };
  };
  myDummy = {
    name: 'know',
    isFolder: false,
    url: 'https://glassy.hackpad.com'
  };
  angular.module('chainApp', ['goban']).constant('$gobanPath', 'https://ethercalc.org/')
  .value('$gobanTitle', 'gl_news').constant('$gobanMax', 3)
  .constant('$dummy', myDummy)
  .controller('chainCtrl', chainCtrl);
}).call(this);
